# Generated by Django 4.2.17 on 2025-01-16 01:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('last_download', models.DateTimeField(auto_now=True)),
                ('last_etag', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raw_offset', models.IntegerField(blank=True, help_text='Raw offset from UTC in seconds', null=True, validators=[django.core.validators.MinValueValidator(-43200), django.core.validators.MaxValueValidator(43200)])),
                ('dst_offset', models.IntegerField(blank=True, help_text='DST offset from UTC in seconds', null=True, validators=[django.core.validators.MinValueValidator(-43200), django.core.validators.MaxValueValidator(43200)])),
                ('timezone_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('aliases', models.TextField(blank=True, help_text='Space-separated list of timezone aliases', null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('iso_country', models.CharField(max_length=2)),
                ('ident', models.CharField(default='', max_length=10)),
                ('type', models.CharField(choices=[('balloonport', 'Balloon Port'), ('closed', 'Closed'), ('heliport', 'Heliport'), ('large_airport', 'Large Airport'), ('medium_airport', 'Medium Airport'), ('seaplane_base', 'Seaplane Base'), ('small_airport', 'Small Airport')], default='small_airport', max_length=20)),
                ('elevation_ft', models.FloatField(blank=True, null=True)),
                ('continent', models.CharField(blank=True, max_length=2, null=True)),
                ('iso_region', models.CharField(blank=True, max_length=10, null=True)),
                ('scheduled_service', models.BooleanField(default=False)),
                ('gps_code', models.CharField(blank=True, max_length=10, null=True)),
                ('local_code', models.CharField(blank=True, max_length=10, null=True)),
                ('home_link', models.URLField(blank=True, max_length=500, null=True)),
                ('wikipedia_link', models.URLField(blank=True, max_length=500, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timezone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airfields', to='airport_info.timezone')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['iata_code'], name='airport_inf_iata_co_91e23f_idx'), models.Index(fields=['ident'], name='airport_inf_ident_176398_idx'), models.Index(fields=['municipality'], name='airport_inf_municip_ed5bc2_idx'), models.Index(fields=['iso_country'], name='airport_inf_iso_cou_d23f35_idx'), models.Index(fields=['iso_region'], name='airport_inf_iso_reg_c8564b_idx'), models.Index(fields=['type'], name='airport_inf_type_9771d6_idx'), models.Index(fields=['updated'], name='airport_inf_updated_8eee57_idx')],
            },
        ),
    ]
