# Generated by Django 5.1.4 on 2025-01-07 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offset', models.IntegerField(help_text='UTC offset in hours', validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(14)])),
                ('uses_dst', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('iata_id', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('iso_country', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airfields', to='airport_info.timezone')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['iata_id'], name='airport_inf_iata_id_bb6a46_idx'), models.Index(fields=['city'], name='airport_inf_city_c243f0_idx'), models.Index(fields=['iso_country'], name='airport_inf_iso_cou_d23f35_idx')],
            },
        ),
    ]
