# Generated by Django 4.2.17 on 2025-01-20 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airport_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
