# Generated by Django 5.1.4 on 2025-01-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_info', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfield',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='airfield',
            index=models.Index(fields=['updated'], name='airport_inf_updated_8eee57_idx'),
        ),
    ]
