# Generated by Django 4.2.17 on 2025-01-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_info', '0002_alter_timezone_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfield',
            name='timezone_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
