# Generated by Django 5.1.4 on 2025-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_info', '0003_airfield_updated_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='airfield',
            name='airport_inf_iata_id_bb6a46_idx',
        ),
        migrations.RemoveIndex(
            model_name='airfield',
            name='airport_inf_city_c243f0_idx',
        ),
        migrations.RenameField(
            model_name='airfield',
            old_name='city',
            new_name='municipality',
        ),
        migrations.RemoveField(
            model_name='airfield',
            name='iata_id',
        ),
        migrations.AddField(
            model_name='airfield',
            name='continent',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='airfield',
            name='elevation_ft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airfield',
            name='gps_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airfield',
            name='home_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='airfield',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='airfield',
            name='ident',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airfield',
            name='iso_region',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airfield',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airfield',
            name='local_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airfield',
            name='scheduled_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airfield',
            name='type',
            field=models.CharField(choices=[('heliport', 'Heliport'), ('small_airport', 'Small Airport'), ('closed', 'Closed')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airfield',
            name='wikipedia_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='airfield',
            index=models.Index(fields=['iata_code'], name='airport_inf_iata_co_91e23f_idx'),
        ),
        migrations.AddIndex(
            model_name='airfield',
            index=models.Index(fields=['ident'], name='airport_inf_ident_176398_idx'),
        ),
        migrations.AddIndex(
            model_name='airfield',
            index=models.Index(fields=['municipality'], name='airport_inf_municip_ed5bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='airfield',
            index=models.Index(fields=['iso_region'], name='airport_inf_iso_reg_c8564b_idx'),
        ),
        migrations.AddIndex(
            model_name='airfield',
            index=models.Index(fields=['type'], name='airport_inf_type_9771d6_idx'),
        ),
    ]
