# Generated by Django 5.1.4 on 2025-01-07 20:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_info', '0006_alter_airfield_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='uses_dst',
        ),
        migrations.AddField(
            model_name='timezone',
            name='dst_offset',
            field=models.IntegerField(blank=True, help_text='DST offset from UTC in seconds', null=True, validators=[django.core.validators.MinValueValidator(-43200), django.core.validators.MaxValueValidator(43200)]),
        ),
        migrations.AddField(
            model_name='timezone',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timezone',
            name='raw_offset',
            field=models.IntegerField(blank=True, help_text='Raw offset from UTC in seconds', null=True, validators=[django.core.validators.MinValueValidator(-43200), django.core.validators.MaxValueValidator(43200)]),
        ),
        migrations.AddField(
            model_name='timezone',
            name='timezone_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timezone',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airfield',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airfields', to='airport_info.timezone'),
        ),
    ]
