# Generated by Django 4.2.17 on 2025-01-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_info', '0007_remove_timezone_offset_remove_timezone_uses_dst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='aliases',
            field=models.TextField(blank=True, help_text='Space-separated list of timezone aliases', null=True),
        ),
    ]
